on: pull_request
name: Review
jobs:
  changelog:
    runs-on: ubuntu-latest
    name: Changelog should be updated
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Git fetch
        run: git fetch

      - name: Check that changelog has been updated.
        run: git diff --exit-code origin/${{ github.base_ref }} -- CHANGELOG.md && exit 1 || exit 0

  markdown-coding-standards:
    name: Markdown coding standards
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Coding standards
        run: |
          docker run --rm --volume "$PWD":/md peterdavehello/markdownlint markdownlint --ignore vendor --ignore LICENSE.md '**/*.md'

  assets-coding-standards:
    name: Assets coding standards
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Coding standards
        run: |
          docker run --volume ${PWD}:/app --rm node:20 yarn --cwd /app install
          docker run --volume ${PWD}:/app --rm node:20 yarn --cwd /app prettier src --check

  audit:
    name: audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: npm audit
        run: |
          npm install
          npm audit

  php-coding-standards:
    name: PHP coding standards
    runs-on: ubuntu-latest
    env:
      # https://getcomposer.org/doc/03-cli.md#composer-auth
      COMPOSER_AUTH: |
        {
          "github-oauth": {
            "github.com": "${{ github.TOKEN }}"
          }
        }
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Coding standards
        run: |
          docker compose run --rm --env COMPOSER_AUTH --user root php composer install
          docker compose run --rm php composer coding-standards-check

  shellcheck:
    runs-on: ubuntu-latest
    name: Shellcheck
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Shellcheck
        run: |
          docker run --rm --tty --volume "$(pwd):/app" peterdavehello/shellcheck shellcheck /app/bin/deploy

  check-create-release:
    runs-on: ubuntu-latest
    name: Test create release
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create test release
        run: |
          ./bin/create-release dev-test
